name:                TemplateHaskellDemo
version:             0.1.0.0
github:              "githubuser/TemplateHaskellDemo"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TemplateHaskellDemo#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.19.0.0
- aeson
- bytestring
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wno-missing-export-lists
- -Wno-unused-imports
- -Wno-unused-matches
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

